Imports System.Data.SqlClient
Imports aspNetEmail
Imports System.IO

Partial Class mobile_SendUpdate
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(sender As Object, e As EventArgs) Handles Me.Load
        If Not IsPostBack Then
            Dim equipmentname As String = ""
            Dim conn As New SqlConnection(appcode.ConnectionString)
            Dim commandString As String
            conn.Open()
            Dim comm As New SqlCommand
            Dim reader As SqlDataReader
            commandString = "select * from t_equipment where equipmentID=@equipmentID"
            comm = New SqlCommand(commandString, conn)
            comm.Parameters.AddWithValue("@equipmentID", Session("mobile_equipmentID"))
            reader = comm.ExecuteReader
            If reader.Read Then
                If reader.Item("equipment_year").ToString <> "" Then
                    equipmentname &= reader.Item("equipment_year") & " "
                End If
                equipmentname &= reader.Item("equipment_oem")
                If reader.Item("equipment_model").ToString <> " " Then
                    equipmentname &= " " & reader.Item("equipment_model")
                End If
                If reader.Item("equipment_description").ToString <> " " Then
                    equipmentname &= " " & reader.Item("equipment_description")
                End If
                equipmentname &= " - " & reader.Item("assetID")
                equipmentlbl.Text = equipmentname
                fromlbl.Text = Session("mobile_user")
            End If
            reader.Close()
            conn.Close()
        End If
    End Sub

    Protected Sub sendbtn_Click(sender As Object, e As EventArgs) Handles sendbtn.Click
        If messagetb.Text <> "" Then
            'Dim m_to As String = userdd.SelectedValue
            Dim m_cc As String = Session("mobile_user_email")
            Dim m_to As String = "ken@dfofilters.com"
            Dim m_bcc As String = ""
            Dim m_from As String = "lubetracker@dfofilters.com"
            Dim m_subject As String = equipmentlbl.Text & " - PRIORITY " & prioritydd.SelectedValue
            Dim m_message As String = "<p>THIS MESSAGE GENERATED BY: " & fromlbl.Text & "</p><p>" & messagetb.Text & "</p>"
            SendEmail(m_subject, m_message, m_from, m_to, m_cc, "")
            appcode.UpdateStatusUpdates(Session("mobile_userID"))
            Response.Redirect("Order.aspx")
        End If
    End Sub

    Sub SendEmail(ByVal subject As String, ByVal message As String, ByVal from As String, ByVal recipient As String, ByVal cc As String, ByVal bcc As String)
        Dim msg As New EmailMessage()
        msg.Server = "localhost"
        msg.FromAddress = from
        msg.ValidateAddress = False
        msg.AddTo(recipient)
        msg.Subject = subject
        If cc <> "" Then
            msg.AddCc(cc)
        End If
        If bcc <> "" Then
            msg.AddBcc(bcc)
        End If
        msg.BodyFormat = MailFormat.Html
        msg.Body = Server.HtmlDecode(message)
        msg.ThrowException = False
        msg.Logging = False
        msg.LogBody = False
        msg.Send()
    End Sub

End Class
